### ISSUE TITLE
LUA Error with simple items

### ISSUE THREAD

**Issue by darhanger** [SacredDuckwhale/TotalAP#37] opened 2017-09-05 07:49 UTC
OMG, when the problem has already been fixed with Otherworldy Trophy or Valiant's Glory? This problem was always. When will it disappear?

Message: Interface\AddOns\TotalAP\Core\Scanner.lua:66: attempt to index local 'm' (a nil value)
Time: 09/05/17 10:38:16
Count: 8
Stack: Interface\AddOns\TotalAP\Core\Scanner.lua:66: attempt to index local 'm' (a nil value)
(tail call): ?
Interface\AddOns\TotalAP\Core\Scanner.lua:66: in function `ParseSpellDesc'
...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:108: in function <...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:34>
...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:156: in function <...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:154>
...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:246: in function <...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:241>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
Locals: <none>

**Comment by rdw-software** [comment] 2017-09-05 08:07
From your comments on Curse, I take it you are using the ruRU client. That one is not supported properly as I can't test it (see issue #7). It will disappear once it is fixed, sorry - I was unable to do it on my own.

It shouldn't be too difficult to fix, but I will need to get the format right. I tried to test the scanning with a level 1 character, but without AK it didn't cover everything - I can try again with the global AK and see if I find out what's wrong - OR you could could take a look at this file [Locales\NumberFormats.lua](https://github.com/SacredDuckwhale/TotalAP/blob/master/Locales/NumberFormats.lua) and fix the entry for ruRU until it works, then I can add it :)

The scanner can break for those locales that are not supported/experimental (ruRU, zhCN at this time)- it shouldn't be limited to any one item, though.

PS: Please don't create duplicate entries/comments - once is enough :) I saw your last comment and created said issue; I was not able to fix it, though, as I don't have a max level character on a Russian realm.

**Comment by rdw-software** [comment] 2017-09-05 18:38
I looked into this some more. I checked all items and there were no errors after removing a bunch of leftovers that for some reason were still in the DB - maybe try the newest release and let me know if there's still something breaking the addon? (47c867dbaa71def154c1a19e899b5f67f25a9eac as included in r26-beta-2)

In that case, please provide me with a screenshot of the item description or at least the item name/ID of the offending item and I will see what I can do.

**Comment by darhanger** [comment] 2017-09-06 04:55
New version, new error

Message: Interface\AddOns\TotalAP\Core\GUI\Tooltips.lua:59: attempt to perform arithmetic on field 'numTomes' (a nil value)
Time: 09/06/17 07:54:19
Count: 4
Stack: Interface\AddOns\TotalAP\Core\GUI\Tooltips.lua:59: attempt to perform arithmetic on field 'numTomes' (a nil value)
[C]: ?
Interface\AddOns\TotalAP\Core\GUI\Tooltips.lua:59: in function <Interface\AddOns\TotalAP\Core\GUI\Tooltips.lua:37>
Interface\AddOns\TotalAP\Core\GUI\Tooltips.lua:125: in function <Interface\AddOns\TotalAP\Core\GUI\Tooltips.lua:123>

Locals:

**Comment by rdw-software** [comment] 2017-09-06 08:40
Is the old one fixed, then? Please create a separate issue to not make things confusing, thanks :)

(I can't reproduce this error, but I'll add a possible fix. Let me know if it still happens in r26-beta-3)

**Comment by rdw-software** [comment] 2017-09-07 07:26
Closing this as a duplicate - the other issue will remain open until its actually fixed.

The unrelated error should be fixed with https://github.com/SacredDuckwhale/TotalAP/commit/9d1d7052d3e31f79e792d39b6348f33b7190a2ec.

**Closed as completed by rdw-software** 2017-09-07 07:26 UTC
Labels: status:duplicate
